#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

. ../../packages/unofficial/retroarch/package.mk

echo "getting sources..."
  if [ ! -d retroarch.git ]; then
    git clone https://github.com/demsullivan/retroarch.git -b wiimote-support retroarch.git
  fi

  cd retroarch.git
    git pull
    GIT_REV=`git log -n1 --format=%h`
  cd ..

echo "copying sources..."
  rm -rf retroarch-$PKG_VERSION
  cp -R retroarch.git retroarch-$PKG_VERSION

echo "cleaning sources..."
  rm -rf retroarch-$PKG_VERSION/.git

echo "packing sources..."
  tar cvJf retroarch-$PKG_VERSION.tar.xz retroarch-$PKG_VERSION

echo "remove temporary sourcedir..."
  rm -rf retroarch-$PKG_VERSION

echo "copying tar balls to sources..."
  if [ ! -d ../../sources ]; then
      mkdir ../../sources
  fi
  if [ ! -d ../../sources/$PKG_NAME/ ]; then
      mkdir ../../sources/$PKG_NAME/
  fi
  mv $PKG_NAME-$PKG_VERSION.tar.xz ../../sources/$PKG_NAME/

echo "generating md5 and url files..."
  cd ../..
  md5sum sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz > sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz.md5
  echo " http://sources.openelec.tv/devel/$PKG_NAME-$PKG_VERSION.tar.xz" > sources/$PKG_NAME/$PKG_NAME-$PKG_VERSION.tar.xz.url
  echo "Source tarballs generated for $PKG_NAME PKG_VERSION=$PKG_VERSION successfully."